on:
  workflow_call:

jobs:
  build-fe:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./property-hub-fe
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build FE
        run: npm install && npm run build

      - name: Upload dist artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist-artifact-fe
          path: property-hub-fe/dist

  build-be:
    runs-on: ubuntu-latest
    steps:
      - name: Swap dirs
        run: echo $(pwd)

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build BE
        run: npm install && npm run build && ./create-lambda-zip.sh

      - name: Upload dist artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist-artifact-be
          path: property-hub-be/nest-lambda.zip
